### ISSUE TITLE
Build script runs npm instead of yarn

### ISSUE THREAD

**Issue by colbyfayock** [nasa/cumulus-dashboard#562]
We seem to be running into a bit of an issue managing the npm dependencies when running the build script here. It looks like there's a `yarn.lock` in the root, however the build script runs `npm install` which doesn't fetch the same versions between different installs (particularly between different team members and our build server in this instance).

Should the build script be referencing yarn? Or perhaps should there be a `package-lock.json` instead of a `yarn.lock`?

Also noticed on the README that the local install uses `yarn` and the specific version uses `npm`, curious if there's a reason behind that? Maybe that helps answer the first question.

Happy to open up a PR to mitigate the issue once we have a little context.

**Comment by markdboyd** [comment]
Thanks for reaching out @colbyfayock 

It looks like the README is just incorrect and should be updated to use `yarn` instead of `npm` all the way through. 

For the build scripts, I assume you mean the `bin/build_in_docker.sh` script? If so, yes, the script should be updated to use `yarn install` instead of `npm install`. But also, the script would need to be updated to include `nvm use` to be on the right version of node specified in `.nvmrc` (8.11) or use a different docker image that is on that node version already. 

We welcome any PRs but we could probably also take a look at this if you don't have time

**Comment by colbyfayock** [comment]
@markdboyd I definitely could throw it together quickly, which do you think would be easier to get it through? (I remember the non-contributer PR process was a little rough at the moment on the other repo) 😃

**Comment by markdboyd** [comment]
@colbyfayock I can work on this today. Hopefully I'll be able to get it taken care of quickly

**Comment by colbyfayock** [comment]
@markdboyd awesome thank you so much! 🙏

**Comment by markdboyd** [comment]
@colbyfayock This is fixed and included in the latest on `master`. And officially released as part of [version 1.4.0](https://github.com/nasa/cumulus-dashboard/releases/tag/v1.4.0)

**Comment by colbyfayock** [comment]
@markdboyd thank you for the heads up 🎉
